### ISSUE TITLE
SMT UAT - PO Type Config

### ISSUE THREAD

**Issue by mandeep-saggi** [mandeep-saggi/PlannerEdge#25]
![Screen Shot 2017-07-06 at 6:33 PM](http://marker.screenshots.prod.s3.amazonaws.com/e638d45c72da4909b85b617fc0b6922d-1499366032950.png)

I was trying to add the PO Type for SMT UAT environment, but there is nowhere for me to add the details. 

Why is this different from PlannerEdge DEV instance?

---
### More Info

**Source URL**: [https://smartm-uat-app.commerzedge.com/planneredge/#/planneredge/transaction-configuration](https://smartm-uat-app.commerzedge.com/planneredge/#/planneredge/transaction-configuration)

<table><tr><td><strong>Browser</strong></td><td>Chrome 59.0.3071.115</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1936 x 1056</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</td></tr></table>

**Comment by gopi-ideas2it** [comment]
@mandeep-saggi  Whenever we first deploy for a client (Smart) We need to configure dynamic function (with respective fields) to the client. This will be done in Radaptive UI. Now I have configured the dynamic function for client in smart-uat.commerzedge.com.
