### ISSUE TITLE
PE DEV - Calculations are incorrect

### ISSUE THREAD

**Issue by mandeep-saggi** [mandeep-saggi/PlannerEdge#26]
The Projected On Hand Inventory is being calculated incorrectly. Please Review the screenshot from PE instance and what the actual calculation should be in the EXCEL sheet. 

![Screen Shot 2017-07-06 at 6:42 PM](http://marker.screenshots.prod.s3.amazonaws.com/bf56d1caf3904a8da185209e60471006-1499366540057.png)

Excel:
![image](https://user-images.githubusercontent.com/29317304/27927433-92d3365a-6240-11e7-85bf-f95c73f4caa9.png)

---
### More Info

**Source URL**: [https://dev-app.commerzedge.com/planneredge/#/planneredge/purchase-request](https://dev-app.commerzedge.com/planneredge/#/planneredge/purchase-request)

<table><tr><td><strong>Browser</strong></td><td>Chrome 59.0.3071.115</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1936 x 1056</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</td></tr></table>

**Comment by gopi-ideas2it** [comment]
@mandeep-saggi  : Current Stock is 1500 which is not in the Excel but available in PlannerEdge screen. Also who have created the Excel.

**Comment by gopi-ideas2it** [comment]
![r500-pl-4018965_2017077_0859](https://user-images.githubusercontent.com/2470918/27942204-b50fe2ce-62f2-11e7-8652-57a08a22eaf4.png)

**Comment by mandeep-saggi** [comment]
@gopi-ideas2it This is my mistake. I did this. I do apologize. When I copy and pasted, somehow the 1500 was missed. 

I will close this issue.
